"""add_mobile_device_tokens

Revision ID: bacf5d0b2df3
Revises: 6b7a85062386
Create Date: 2026-06-08 13:38:25.443718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacf5d0b2df3'
down_revision = '6b7a85062386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mobile_device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mobile_device_tokens_fcm_token'), ['fcm_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_mobile_device_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_device_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_mobile_device_tokens_fcm_token'))

    op.drop_table('mobile_device_tokens')
    # ### end Alembic commands ###
